name = '  simon jordan  '

print(name)
print(name.capitalize())
print(name.title())
print(name.upper())
print(name.lower())
print(name.title().swapcase())
print(name.rstrip())
print(name.lstrip())
print(name.strip())
print(name.ljust(30, 'X'))
print(name.rjust(20, 'X'))
print(name.replace('o', 'e'))
print(name.join('hello'))
print(name.center(30, '/'))
print(name.count('o'))
print(name.find('o'))
print(name.find('q'))
print(name.startswith('S'))
print(name.strip().startswith('S'))
print(name.strip().capitalize().startswith('S'))
print(name.ljust(20, 'x').endswith('x'))
print(name.isalpha())
print(name.isnumeric())
print(name.isalnum())
print(name.strip().replace(' ', '').isalnum())
